Fix the error message for too long buffer unit filenames on Windows
Introduce a dedicated exception handler and call to Fatal_Error for the
Windows-specific code path exercised by this precise situation.

The global exception handler in gnatcov_bits_specific.adb now uses
Switches.Exception_Info, which expectedly include the name of the raised
exception: this is not appropriate for user-level error messages, as
exception names look like crashes when printed.

(cherry picked from commit 565ec16856453830f6954c24f5dc261b7bc7ec8f)